services:
  db:
    image: postgres:15
    container_name: bioquimicaunc-db
    restart: always
    environment:
      POSTGRES_USER: bioquimicaunc_user
      POSTGRES_PASSWORD: bioquimicaunc_pass
      POSTGRES_DB: bioquimicaunc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
