services:
  db:
    image: postgres:15
    container_name: bioquimicaunc-db
    restart: always
    environment:
      POSTGRES_USER: bioquimicaunc_user
      POSTGRES_PASSWORD: bioquimicaunc_pass
      POSTGRES_DB: bioquimicaunc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bioquimicaunc-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: bioquimicaunc_user
      DB_PASSWORD: bioquimicaunc_pass
      DB_DATABASE: bioquimicaunc_db
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

volumes:
  postgres_data:
